### ISSUE TITLE
provide binary

### ISSUE THREAD

**Issue by adryzz** [avocadoboi/AvoExplorer#1]
can u compile it and make a release?
i have vs 2019 set up, but not everyone has this

**Comment by avocadoboi** [comment]
Hello! Thank you for reminding me, this may be a good time to do that since the bookmark and file browsing system is coming together. Note that there is still some important functionality that hasn't been implemented yet (adding/moving files), but will be in the near future.

**Comment by avocadoboi** [comment]
Done!

**Comment by adryzz** [comment]
thanks!
